[build]
  command = "npm run build:netlify"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "https://dino404.netlify.app/*"
  to = "https://dino404.xyz/:splat"
  status = 301
  force = true

[dev]
  command = "npm run dev:netlify"
  targetPort = 3000
  port = 8888
  framework = "next"
